2021-04-20 11:14:43,312 INFO    MainThread:12779 [wandb_setup.py:_flush():69] setting env: {}
2021-04-20 11:14:43,312 INFO    MainThread:12779 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-20 11:14:43,312 INFO    MainThread:12779 [wandb_init.py:_log_setup():336] Logging user logs to /home/ubuntuadm/trainseg/utils/wandb/run-20210420_111443-2ho6wm15/logs/debug.log
2021-04-20 11:14:43,312 INFO    MainThread:12779 [wandb_init.py:_log_setup():337] Logging internal logs to /home/ubuntuadm/trainseg/utils/wandb/run-20210420_111443-2ho6wm15/logs/debug-internal.log
2021-04-20 11:14:43,313 INFO    MainThread:12779 [wandb_init.py:init():369] calling init triggers
2021-04-20 11:14:43,313 INFO    MainThread:12779 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-20 11:14:43,313 INFO    MainThread:12779 [wandb_init.py:init():418] starting backend
2021-04-20 11:14:43,313 INFO    MainThread:12779 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-20 11:14:43,330 INFO    MainThread:12779 [backend.py:ensure_launched():123] starting backend process...
2021-04-20 11:14:43,337 INFO    MainThread:12779 [backend.py:ensure_launched():127] started backend process with pid: 12794
2021-04-20 11:14:43,342 INFO    MainThread:12779 [wandb_init.py:init():423] backend started and connected
2021-04-20 11:14:43,344 INFO    MainThread:12779 [wandb_init.py:init():465] updated telemetry
2021-04-20 11:14:43,345 INFO    MainThread:12779 [wandb_init.py:init():484] communicating current version
2021-04-20 11:14:44,369 INFO    MainThread:12779 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.27 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-04-20 11:14:44,369 INFO    MainThread:12779 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-20 11:14:44,588 INFO    MainThread:12779 [wandb_init.py:init():522] starting run threads in backend
2021-04-20 11:14:46,229 INFO    MainThread:12779 [wandb_run.py:_console_start():1524] atexit reg
2021-04-20 11:14:46,229 INFO    MainThread:12779 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-20 11:14:46,229 INFO    MainThread:12779 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-20 11:14:46,238 INFO    MainThread:12779 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-20 11:14:46,238 INFO    MainThread:12779 [wandb_init.py:init():546] run started, returning control to user process
2021-04-20 11:14:46,238 INFO    MainThread:12779 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-20 11:14:46,239 INFO    MainThread:12779 [wandb_run.py:_restore():1466] restore
2021-04-20 11:14:48,524 INFO    MainThread:12779 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 915
  total_bytes: 915
}

2021-04-20 11:14:49,594 INFO    MainThread:12779 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 915
  total_bytes: 3496
}

2021-04-20 11:14:49,892 INFO    MainThread:12779 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3496
  total_bytes: 3496
}

2021-04-20 11:14:49,994 INFO    MainThread:12779 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3496
  total_bytes: 3496
}

2021-04-20 11:14:50,096 INFO    MainThread:12779 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3496
  total_bytes: 3496
}

2021-04-20 11:14:50,197 INFO    MainThread:12779 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3496
  total_bytes: 3496
}

2021-04-20 11:14:50,299 INFO    MainThread:12779 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3496
  total_bytes: 3496
}

2021-04-20 11:14:50,401 INFO    MainThread:12779 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3496
  total_bytes: 3496
}

2021-04-20 11:14:51,844 INFO    MainThread:12779 [wandb_run.py:_show_files():1838] logging synced files
