2021-04-16 16:50:33,890 INFO    MainThread:31083 [wandb_setup.py:_flush():69] setting env: {}
2021-04-16 16:50:33,890 INFO    MainThread:31083 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-16 16:50:33,890 INFO    MainThread:31083 [wandb_init.py:_log_setup():336] Logging user logs to /home/ubuntuadm/trainseg/utils/wandb/run-20210416_165033-1l9h4c69/logs/debug.log
2021-04-16 16:50:33,890 INFO    MainThread:31083 [wandb_init.py:_log_setup():337] Logging internal logs to /home/ubuntuadm/trainseg/utils/wandb/run-20210416_165033-1l9h4c69/logs/debug-internal.log
2021-04-16 16:50:33,890 INFO    MainThread:31083 [wandb_init.py:init():369] calling init triggers
2021-04-16 16:50:33,890 INFO    MainThread:31083 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-16 16:50:33,890 INFO    MainThread:31083 [wandb_init.py:init():418] starting backend
2021-04-16 16:50:33,890 INFO    MainThread:31083 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-16 16:50:33,907 INFO    MainThread:31083 [backend.py:ensure_launched():123] starting backend process...
2021-04-16 16:50:33,918 INFO    MainThread:31083 [backend.py:ensure_launched():127] started backend process with pid: 31098
2021-04-16 16:50:33,925 INFO    MainThread:31083 [wandb_init.py:init():423] backend started and connected
2021-04-16 16:50:33,927 INFO    MainThread:31083 [wandb_init.py:init():465] updated telemetry
2021-04-16 16:50:33,930 INFO    MainThread:31083 [wandb_init.py:init():484] communicating current version
2021-04-16 16:50:35,157 INFO    MainThread:31083 [wandb_init.py:init():489] got version response 
2021-04-16 16:50:35,157 INFO    MainThread:31083 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-16 16:50:35,375 INFO    MainThread:31083 [wandb_init.py:init():522] starting run threads in backend
2021-04-16 16:50:37,253 INFO    MainThread:31083 [wandb_run.py:_console_start():1524] atexit reg
2021-04-16 16:50:37,254 INFO    MainThread:31083 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-16 16:50:37,254 INFO    MainThread:31083 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-16 16:50:37,259 INFO    MainThread:31083 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-16 16:50:37,259 INFO    MainThread:31083 [wandb_init.py:init():546] run started, returning control to user process
2021-04-16 18:28:01,049 INFO    MainThread:31083 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-16 18:28:01,050 INFO    MainThread:31083 [wandb_run.py:_restore():1466] restore
2021-04-16 18:28:03,328 INFO    MainThread:31083 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 834
  total_bytes: 834
}

2021-04-16 18:28:03,985 INFO    MainThread:31083 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 834
  total_bytes: 1279
}

2021-04-16 18:28:04,353 INFO    MainThread:31083 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3665
  total_bytes: 3665
}

2021-04-16 18:28:04,455 INFO    MainThread:31083 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3665
  total_bytes: 3665
}

2021-04-16 18:28:04,560 INFO    MainThread:31083 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3665
  total_bytes: 3665
}

2021-04-16 18:28:04,662 INFO    MainThread:31083 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3665
  total_bytes: 3665
}

2021-04-16 18:28:04,764 INFO    MainThread:31083 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3665
  total_bytes: 3665
}

2021-04-16 18:28:04,866 INFO    MainThread:31083 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3665
  total_bytes: 3665
}

2021-04-16 18:28:04,968 INFO    MainThread:31083 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3665
  total_bytes: 3665
}

2021-04-16 18:28:06,386 INFO    MainThread:31083 [wandb_run.py:_show_summary():1771] rendering summary
2021-04-16 18:28:06,386 INFO    MainThread:31083 [wandb_run.py:_show_history():1809] rendering history
2021-04-16 18:28:06,388 INFO    MainThread:31083 [wandb_run.py:_show_files():1838] logging synced files
