2021-04-17 11:12:57,701 INFO    MainThread:35129 [wandb_setup.py:_flush():69] setting env: {}
2021-04-17 11:12:57,701 INFO    MainThread:35129 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-17 11:12:57,701 INFO    MainThread:35129 [wandb_init.py:_log_setup():336] Logging user logs to /home/ubuntuadm/trainseg/utils/wandb/run-20210417_111257-iqtb0wux/logs/debug.log
2021-04-17 11:12:57,701 INFO    MainThread:35129 [wandb_init.py:_log_setup():337] Logging internal logs to /home/ubuntuadm/trainseg/utils/wandb/run-20210417_111257-iqtb0wux/logs/debug-internal.log
2021-04-17 11:12:57,702 INFO    MainThread:35129 [wandb_init.py:init():369] calling init triggers
2021-04-17 11:12:57,702 INFO    MainThread:35129 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-17 11:12:57,702 INFO    MainThread:35129 [wandb_init.py:init():418] starting backend
2021-04-17 11:12:57,702 INFO    MainThread:35129 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-17 11:12:57,717 INFO    MainThread:35129 [backend.py:ensure_launched():123] starting backend process...
2021-04-17 11:12:57,726 INFO    MainThread:35129 [backend.py:ensure_launched():127] started backend process with pid: 35144
2021-04-17 11:12:57,733 INFO    MainThread:35129 [wandb_init.py:init():423] backend started and connected
2021-04-17 11:12:57,734 INFO    MainThread:35129 [wandb_init.py:init():465] updated telemetry
2021-04-17 11:12:57,740 INFO    MainThread:35129 [wandb_init.py:init():484] communicating current version
2021-04-17 11:12:58,477 INFO    MainThread:35129 [wandb_init.py:init():489] got version response 
2021-04-17 11:12:58,477 INFO    MainThread:35129 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-17 11:12:58,703 INFO    MainThread:35129 [wandb_init.py:init():522] starting run threads in backend
2021-04-17 11:13:00,269 INFO    MainThread:35129 [wandb_run.py:_console_start():1524] atexit reg
2021-04-17 11:13:00,270 INFO    MainThread:35129 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-17 11:13:00,270 INFO    MainThread:35129 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-17 11:13:00,300 INFO    MainThread:35129 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-17 11:13:00,301 INFO    MainThread:35129 [wandb_init.py:init():546] run started, returning control to user process
2021-04-17 13:04:10,974 INFO    MainThread:35129 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-04-17 13:04:10,975 INFO    MainThread:35129 [wandb_run.py:_restore():1466] restore
2021-04-17 13:04:13,170 INFO    MainThread:35129 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 834
  total_bytes: 834
}

2021-04-17 13:04:14,018 INFO    MainThread:35129 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 834
  total_bytes: 3654
}

2021-04-17 13:04:14,346 INFO    MainThread:35129 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3654
  total_bytes: 3654
}

2021-04-17 13:04:14,448 INFO    MainThread:35129 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3654
  total_bytes: 3654
}

2021-04-17 13:04:14,550 INFO    MainThread:35129 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3654
  total_bytes: 3654
}

2021-04-17 13:04:14,652 INFO    MainThread:35129 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3654
  total_bytes: 3654
}

2021-04-17 13:04:14,754 INFO    MainThread:35129 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3654
  total_bytes: 3654
}

2021-04-17 13:04:14,855 INFO    MainThread:35129 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 3654
  total_bytes: 3654
}

2021-04-17 13:04:16,252 INFO    MainThread:35129 [wandb_run.py:_show_summary():1771] rendering summary
2021-04-17 13:04:16,252 INFO    MainThread:35129 [wandb_run.py:_show_history():1809] rendering history
2021-04-17 13:04:16,253 INFO    MainThread:35129 [wandb_run.py:_show_files():1838] logging synced files
